In [1]:
import pandas as pd
import numpy as np

In [2]:
temp_df = pd.read_csv('IMDB Dataset.csv')

In [3]:
df = temp_df.iloc[:1000]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     1000 non-null   object
 1   sentiment  1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB


In [5]:
df.sentiment.value_counts()

positive    501
negative    499
Name: sentiment, dtype: int64

In [6]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [7]:
df.sentiment.unique()

array(['positive', 'negative'], dtype=object)

In [8]:
df.sentiment = df.sentiment.map({'positive':1, 'negative':0})

C:\Users\ACER\AppData\Local\Temp\ipykernel_5764\1676240007.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.sentiment = df.sentiment.map({'positive':1, 'negative':0})


In [9]:
df

review  sentiment
0    One of the other reviewers has mentioned that ...          1
1    A wonderful little production. <br /><br />The...          1
2    I thought this was a wonderful way to spend ti...          1
3    Basically there's a family where a little boy ...          0
4    Petter Mattei's "Love in the Time of Money" is...          1
..                                                 ...        ...
995  Nothing is sacred. Just ask Ernie Fosselius. T...          1
996  I hated it. I hate self-aware pretentious inan...          0
997  I usually try to be professional and construct...          0
998  If you like me is going to see this in a film ...          0
999  This is like a zoology textbook, given that it...          0

[1000 rows x 2 columns]

In [10]:
df.duplicated().sum()

0

In [11]:
df.sentiment = df.sentiment.astype('int8')

C:\Users\ACER\AppData\Local\Temp\ipykernel_5764\558975556.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.sentiment = df.sentiment.astype('int8')


In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     1000 non-null   object
 1   sentiment  1000 non-null   int8  
dtypes: int8(1), object(1)
memory usage: 8.9+ KB


In [13]:
df['review'] = df['review'].str.lower()

C:\Users\ACER\AppData\Local\Temp\ipykernel_5764\724319867.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].str.lower()


In [14]:
import re
def remove_tags(text):
    cleaned_text = re.sub(re.compile('<.*?>'),'',text)
    return cleaned_text

In [15]:
df['review'] = df['review'].apply(remove_tags)

C:\Users\ACER\AppData\Local\Temp\ipykernel_5764\2336150696.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_tags)


In [16]:
from nltk.corpus import stopwords
stopwords.words('english')


['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [17]:
def remove_stopwords(text):
    words = text.split()
    new_text = []
    for word in words:
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return ' '.join(x)

In [19]:
df['review'] = df['review'].apply(remove_stopwords)

C:\Users\ACER\AppData\Local\Temp\ipykernel_5764\3992406652.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_stopwords)


In [20]:
df

review  sentiment
0    one    reviewers  mentioned   watching  1 oz e...          1
1     wonderful little production.  filming techniq...          1
2     thought    wonderful way  spend time    hot s...          1
3    basically there's  family   little boy (jake) ...          0
4    petter mattei's "love   time  money"   visuall...          1
..                                                 ...        ...
995  nothing  sacred.  ask ernie fosselius.  days, ...          1
996   hated it.  hate self-aware pretentious inanit...          0
997   usually try   professional  constructive   cr...          0
998    like   going  see    film history class  som...          0
999    like  zoology textbook, given   depiction  a...          0

[1000 rows x 2 columns]

In [24]:
X = df[['review']]

In [25]:
y = df.sentiment

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [30]:
from sklearn.feature_extraction.text import CountVectorizer
model = CountVectorizer()

In [44]:
X_trainBOW = model.fit_transform(X_train['review']).toarray()

In [62]:
X_trainBOW.shape

(750, 15434)

In [46]:
X_testBOW = model.transform(X_test['review']).toarray()

In [48]:
from sklearn.naive_bayes import GaussianNB

In [49]:
GNB = GaussianNB()

In [50]:
GNB.fit(X_trainBOW,y_train)

GaussianNB()

In [52]:
predicted = GNB.predict(X_testBOW)

In [53]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [54]:
accuracy_score(y_test,predicted)

0.568

In [55]:
confusion_matrix(y_test,predicted)

array([[67, 62],
       [46, 75]], dtype=int64)

In [56]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier()

In [57]:
RF.fit(X_trainBOW,y_train)

RandomForestClassifier()

In [59]:
y_predict = RF.predict(X_testBOW)

In [60]:
accuracy_score(y_test, y_predict)

0.784

In [65]:
model = CountVectorizer(max_features=3000)   #3000 Words having more frequency tthan other words.
X_trainBOW = model.fit_transform(X_train['review']).toarray()
X_testBOW = model.transform(X_test['review']).toarray()
RF = RandomForestClassifier()
RF.fit(X_trainBOW,y_train)
RF.predict(X_testBOW)
accuracy_score(y_test,RF.predict(X_testBOW))

0.82

# N-Gram

In [69]:
model = CountVectorizer(ngram_range=(1,2),max_features=3000)
X_trainBOW = model.fit_transform(X_train['review']).toarray()
X_testBOW = model.transform(X_test['review']).toarray()
RF = RandomForestClassifier()
RF.fit(X_trainBOW,y_train)
RF.predict(X_testBOW)
accuracy_score(y_test,RF.predict(X_testBOW))

0.796

# TF-IDF

In [70]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [71]:
tfidf = TfidfVectorizer()
X_train_tfidf = model.fit_transform(X_train['review']).toarray()
X_test_tfidf = model.transform(X_test['review']).toarray()
RF = RandomForestClassifier()
RF.fit(X_train_tfidf,y_train)
RF.predict(X_test_tfidf)
accuracy_score(y_test,RF.predict(X_test_tfidf))

0.808

# Word2Vec

In [73]:
import gensim
import os

In [74]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

story = []  
for doc in df['review']:
    raw_sent = sent_tokenize(doc)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))
        ## for training Word2Vec and converting all the words to Vector

In [75]:
model = gensim.models.Word2Vec(window = 10, min_count = 2)

In [76]:
model.build_vocab(story) # building vocabualry

In [77]:
model.train(story, total_examples=model.corpus_count, epochs = model.epochs)

(557297, 623495)

In [78]:
len(model.wv.index_to_key)

9395

In [80]:
def document_vector(doc):
    doc = [word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc], axis = 0)

In [82]:
document_vector(df['review'].values[0]) # Changing review into vectors

array([-2.36698061e-01,  4.02776718e-01,  3.30440514e-02,  4.72890362e-02,
        7.76553713e-03, -5.14368236e-01,  2.41301924e-01,  8.81005466e-01,
       -3.25092882e-01, -2.59819359e-01, -1.88817441e-01, -6.83933854e-01,
       -2.11867336e-02,  2.09282517e-01,  8.07491615e-02, -4.08085078e-01,
        2.57968437e-02, -6.24778628e-01,  1.04063183e-01, -7.97637999e-01,
        1.91154376e-01,  2.20494553e-01,  1.97056100e-01, -8.59235600e-02,
       -1.44568279e-01, -4.49668951e-02, -2.65542209e-01, -1.38662279e-01,
       -2.77025282e-01,  4.19082940e-02,  4.66859102e-01,  9.22011659e-02,
        7.17607737e-02, -9.30165499e-02, -1.60778031e-01,  3.55952680e-01,
        1.29090220e-01, -2.23440439e-01, -1.86664984e-01, -7.23811209e-01,
        5.22945635e-02, -3.78934413e-01, -5.08933403e-02, -1.53937051e-02,
        2.81127542e-01, -2.60792702e-01, -2.55084932e-01, -8.70101228e-02,
        1.63880348e-01,  3.19647402e-01,  1.06313653e-01, -3.89257371e-01,
       -2.86842555e-01, -

In [86]:
from tqdm import tqdm

In [87]:
A = []
for doc in tqdm(df['review'].values):
    A.append(document_vector(doc))


100%|██████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:13<00:00, 74.58it/s]


In [88]:
A =np.array(A)

In [90]:
A.shape

(1000, 100)

In [94]:
y = df.sentiment

In [95]:
X_train, X_test, y_train, y_test = train_test_split(A, y, test_size=0.25, random_state=42)

In [97]:
rf = RandomForestClassifier()

In [98]:
rf.fit(X_train,y_train)

RandomForestClassifier()

In [99]:
rf.predict(X_test)

array([0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1], dtype=int8)

In [100]:
accuracy_score(y_test,rf.predict(X_test))

0.608